# Generated by Django 6.0.2 on 2026-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram username of the reviewer (optional)', max_length=100, null=True),
        ),
    ]
