# Generated by Django 6.0.2 on 2026-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_review_instagram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Custom profile picture (optional)', null=True, upload_to='profile_pics/'),
        ),
    ]
